### ISSUE TITLE
Slow running

### ISSUE THREAD

**Issue by patricksmms** [mainfraame/cucumber-jest#10]
With a small set of 37 tests, with steps split in 6 files, it's taking almost a second to run each test (~35seconds to run all).
I experimented joining all steps in a single file, the time reduced about 10 seconds.
Recreating the same tests, without `cucumber` and `cucumber-jest`, takes roughly half of the time (~18 seconds to run all).
I tried replacing `ts-jest`with `babel-jest`, setting `---maxWorkers=1`, `--runInBand`, neither helped on the performance.

Perhaps caching the transformations would help?

**Comment by mainfraame** [comment]
@patricksmms i agree that caching could help. 

Here’s where the pain points are:

https://github.com/mainfraame/cucumber-jest/blob/9a8b01d7785d494954dd4960a9b3eb63bb504b16/src/parsers/feature.ts#L8

That should require opting into. It calls glob.sync, which is taxing. 

https://github.com/mainfraame/cucumber-jest/blob/9a8b01d7785d494954dd4960a9b3eb63bb504b16/src/parsers/suite.ts#L37

I’m not certain, but I would suspect this also takes time. If that’s the case, we would need to figure out how to serialize the spec object for caching and re-hydrate it later on.  I’ve seen some relatively safe techniques using ‘’’Function(‘return ${fn.toString()}’)’’’ for functions.  

I’ll take a closer look when I get some free time.

**Comment by mainfraame** [comment]
@patricksmms I took a closer look using the following example features with perf_hooks (milliseconds):

- Full Tests Executed Using Example Project's Feature Files

- Feature W/ Variables: [scenarioOutlineNestedGlobal](https://github.com/mainfraame/cucumber-jest/blob/master/example/test/features/scenarioOutlineNestedGlobal.feature)

- Feature W/Out Variables: [scenario](https://github.com/mainfraame/cucumber-jest/blob/master/example/test/features/scenario.feature)

1 - Initial performance measurements:

```
getVariables: 926.183918      // <--- culprit
generateMessages: 5.46088

parseSuite (total): 937.094623
```

```
Test Suites: 9 passed, 9 total
Tests:       17 skipped, 140 passed, 157 total
Snapshots:   0 total
Time:        9.764 s
```

2 - After refactoring the two different glob calls made into to a single glob and excluding node_modules folder:

Best Run
```
getVariables: 24.253767
generateMessages: 6.486279

parseSuite (total): 36.53057
```

Worst Run (initial/first run)
```
getVariables: 37.478636
generateMessages: 6.26386

parseSuite (total): 47.315788
```

3 - With the same optimizations described in 2, but adding an environment flag to opt-in to variables (w/out variables):

Best Run
```
getVariables: 0.024499
generateMessages: 5.235965

parseSuite (total): 8.457269
```

Worst Run
```
getVariables: 0.061103
generateMessages: 5.234747

parseSuite (total): 8.922798
```

4 - Applying optimizations described above and executing all example tests **w/ variables on**:

Best Run
```
Test Suites: 9 passed, 9 total
Tests:       17 skipped, 140 passed, 157 total
Snapshots:   0 total
Time:        7.492 s
```

Worst Run
```
Test Suites: 9 passed, 9 total
Tests:       17 skipped, 140 passed, 157 total
Snapshots:   0 total
Time:        7.619 s
```

5 - Applying optimizations described above and executing all example tests **w/ variables off**:

Best Run
```
Test Suites: 9 passed, 9 total
Tests:       17 skipped, 140 passed, 157 total
Snapshots:   0 total
Time:        7.465 s
```

Worst Run
```
Test Suites: 9 passed, 9 total
Tests:       17 skipped, 140 passed, 157 total
Snapshots:   0 total
Time:        7.542 s
```

Conclusion:

Optimizing the glob calls seems to have had the greatest impact. However, I believe the cost of adding the "opt-in" for variables does not out-weight the benefit.  I'll work tonight on pushing up these changes and getting a release out. 

I'll keep this ticket open after the release. If you don't mind, could you try and execute the same set of tests you described with this latest release and report back here?

Thanks again for your contributions.

**Comment by mainfraame** [comment]
@patricksmms it is published. let me know how the performance with the changes...

**Comment by patricksmms** [comment]
Unfortunately these changes didn't seem to have any impact here. It's still taking the same amount of time. I'm trying to figure out where the bottleneck is, I'll let you know in case I find it.

**Comment by patricksmms** [comment]
![image](https://user-images.githubusercontent.com/17434816/109327737-f0f56000-7858-11eb-9681-c6c2a5cea8f0.png)

**Comment by mainfraame** [comment]
Interesting. Any chance you could push up a branch with the tests you’re running?  I’m curious if it’s related to the fact that everything is getting transpiled before each test. I’ve used the globalSetup and globalTeardown configs for jest before and it might be worth taking a look to see if we can’t transpile the steps ahead of time, instead of doing that for each test. 

Here’s an example they provide for puppeteer:

https://jestjs.io/docs/en/puppeteer#custom-example-without-jest-puppeteer-preset

**Comment by patricksmms** [comment]
@mainfraame, unfortunately I can't share any of the source code, this is proprietary software. But anyway: the graph shows, and I could confirm by running tests excluding a thing at a time, that the culprits are Rendering, Querying elements and the initial Require of modules initially. So nothing to do with your jest transformer.
This is a complex component, that imports many libs. I was trying to do this unorthodox thing of testing it without having to build the full app and rendering on a browser, but it doesn't seem viable.
I apologies taking your time to investigate it, and really appreciate your collaboration.

**Comment by mainfraame** [comment]
@patricksmms thanks for the vindication.  I've definitely came across the same issues you're facing.

**Querying Elements** - I managed to improve performance by using a class based approach, similar to the [Element](https://github.com/mainfraame/cucumber-jest/blob/master/example/test/element.ts#L14) class in the examples folder. I additionally added a caching layer where I would set the element on a class property and check the **isConnected** property on the element before querying again.  This property has been in JSDOM since version [13.1.0](https://github.com/jsdom/jsdom/blob/master/Changelog.md#1310).

**Transpiling For Each Test Case** - The one pitfall of jest is that it uses a new [vm instance](https://nodejs.org/api/vm.html) for each test file. This is marginally helped by jest's caching of imports, but that only goes so far. This approach can lead to long wait times for compilation/transpilation between tests; depending on the size of your application.  Transpiling ahead of time is a viable option, but it makes coverage difficult, if not impossible.

**Mitigating Long Run Times** - When I used this transformer for jsdom and puppeteer testing of a large enterprise app, I setup background steps that avoided repeating actions when unnecessary. For Example (puppeteer), if you have background steps that login and go to a page, I would add logic to prevent re-logging in (if already logged in) and avoid navigating to the page (if I was already on the page). For integration (jsdom) tests that fired up the whole app, I would avoid using steps to do any mounting/unmounting of the application and instead used the beforeAll / afterAll hooks to do that. 

**Testing A Page Out Of An App** -  In one particular app I used this for testing, I was able to create a testing harness/wrapper component that I could render with a single page. It would provide stuff like any context providers (eg, redux, react-router, etc.).  If you're using params/query params from react router context, you can even spoof it to think it's on a page by simply updating the hash or path set in jsdom. 

**Alternative Transformers** - I'm not sure if you're aware, but [esbuild](https://github.com/aelbore/esbuild-jest) is a far-faster alternative to babel.  It uses an embedded GO script to transpile. It's benchmarks as impressive compare to babel and webpack.  It might be worth looking into as an alternative to help speed things up.

It's been my experience that integration testing in general is far more resource intensive (including time) than unit testing; whether you're using cucumber or not. Some of things I've mentioned above should help, but there is no magic bullet to solve the issue.  Hopefully it helps...

**Comment by patricksmms** [comment]
@mainfraame thanks a lot! I'll definitely try your suggestions. I'm now also looking at replacing jsdom with [linkedom](https://github.com/WebReflection/linkedom). In case it has a good DOM support, then it might help significantly on the rendering time and querying elements on the page.
